### ISSUE TITLE
OpenURL doesn’t work

### ISSUE THREAD

**Issue by rcyggdra** [matyalatte/Simple-Command-Runner#17]
version 0.5.0

Clicking the “Help -> Url” button will crash;
same as "Open File".

**Comment by matyalatte** [comment]
Sorry, I forgot to test that feature.

Fixed at af2597045b3920ac0cc8e9c51cacf1db605546e8. And here are the fixed builds.
[SimpleCommandRunner-v0.5.0-hotfix-Windows.zip](https://github.com/matyalatte/Simple-Command-Runner/files/12002708/SimpleCommandRunner-v0.5.0-hotfix-Windows.zip)
[SimpleCommandRunner-v0.5.0-hotfix-macOS.zip](https://github.com/matyalatte/Simple-Command-Runner/files/12002735/SimpleCommandRunner-v0.5.0-hotfix-macOS.zip)

**Comment by rcyggdra** [comment]
> Sorry, I forgot to test that feature.
> 
> Fixed at [af25970](https://github.com/matyalatte/Simple-Command-Runner/commit/af2597045b3920ac0cc8e9c51cacf1db605546e8). And here are the fixed builds. [SimpleCommandRunner-v0.5.0-hotfix-Windows.zip](https://github.com/matyalatte/Simple-Command-Runner/files/12002708/SimpleCommandRunner-v0.5.0-hotfix-Windows.zip) [SimpleCommandRunner-v0.5.0-hotfix-macOS.zip](https://github.com/matyalatte/Simple-Command-Runner/files/12002735/SimpleCommandRunner-v0.5.0-hotfix-macOS.zip)

it's working,thank you.

**Comment by matyalatte** [comment]
The fixed builds were released as [v0.5.0-hotfix](https://github.com/matyalatte/Simple-Command-Runner/releases/tag/af25970).
Thank you for the report.
