### ISSUE TITLE
How to use more than one files

### ISSUE THREAD

**Issue by enarkay** [matyalatte/Simple-Command-Runner#9]
None of the examples showed what to do if I had more than one files, or more than one of any type.
For example, if I have two file variables to include in the command, what do I do??

I tried "somecommand %file% %file%" but the program ran into an error and crashed.

**Comment by enarkay** [comment]
Never mind, I found out that it was my native language(Korean) that was breaking the program. Using Korean on the labels seems to break the program. If you could perhaps add support for languages/characters other than English in the future, it would be great, but for now I can do with using English labels. Thank you for such a great and convenient tool! :)

**Comment by matyalatte** [comment]
Thanks for the report.
I found out it's a bug for v0.2.2.
I'll fix it later, but v0.2.1 will work with Korean strings, I think.

**Comment by enarkay** [comment]
> Thanks for the report. I found out it's a bug for v0.2.2. I'll fix it later, but [v0.2.1](https://github.com/matyalatte/Simple-Command-Runner/releases/tag/v0.2.1) will work with Korean strings, I think.

I've tested and confirmed that Korean characters do work in v0.2.1 - thank you for the info! :)

**Comment by matyalatte** [comment]
Fixed at fdd672c.
The built binaries are available as [v0.2.3](https://github.com/matyalatte/Simple-Command-Runner/releases/tag/v0.2.3).
